<a href="https://colab.research.google.com/github/archanaudhaya/Datasciencetask/blob/main/Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to combine last element with first element of two given ndarray
with different shapes.
Sample Output:
Original arrays:
['PHP', 'JS', 'C++']
['Python', 'C#', 'NumPy']
After Combining:
['PHP' 'JS' 'C++Python' 'C#' 'NumPy']

In [ ]:
import numpy as np

# Given arrays
array1 = np.array(['PHP', 'JS', 'C++'])
array2 = np.array(['Python', 'C#', 'NumPy'])

# Combine last element of array1 with the first element of array2
combined_array = np.concatenate([array1[:-1], np.array([array1[-1] + array2[0]]), array2[1:]])

# Print the original and combined arrays
print("Original arrays:")
print(array1)
print(array2)
print("After Combining:")
print(combined_array)

Original arrays:
['PHP' 'JS' 'C++']
['Python' 'C#' 'NumPy']
After Combining:
['PHP' 'JS' 'C++Python' 'C#' 'NumPy']


a. Write a NumPy program to convert an array to a float type

In [ ]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
float_array = original_array.astype(float)

print("Original Array:")
print(original_array)
print("Float Array:")
print(float_array)

Original Array:
[1 2 3 4 5]
Float Array:
[1. 2. 3. 4. 5.]


b. Write a NumPy program to create an empty and a full array

In [ ]:
import numpy as np

empty_array = np.empty((3, 3))
full_array = np.full((2, 2), 7)

print("Empty Array:")
print(empty_array)
print("Full Array:")
print(full_array)

Empty Array:
[[4.96776481e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
Full Array:
[[7 7]
 [7 7]]


c. Write a NumPy program to convert a list and tuple into arrays

In [ ]:
import numpy as np

list_data = [1, 2, 3, 4]
tuple_data = ((1, 2, 3), (4, 5, 6))

array_from_list = np.array(list_data)
array_from_tuple = np.array(tuple_data)

print("Array from List:")
print(array_from_list)
print("Array from Tuple:")
print(array_from_tuple)

Array from List:
[1 2 3 4]
Array from Tuple:
[[1 2 3]
 [4 5 6]]


d. Write a NumPy program to find the real and imaginary parts of an array of complex numbers

In [ ]:
import numpy as np

complex_array = np.array([1 + 2j, 3 + 4j, 5 + 6j])

real_parts = np.real(complex_array)
imaginary_parts = np.imag(complex_array)

print("Complex Array:")
print(complex_array)
print("Real Parts:")
print(real_parts)
print("Imaginary Parts:")
print(imaginary_parts)

Complex Array:
[1.+2.j 3.+4.j 5.+6.j]
Real Parts:
[1. 3. 5.]
Imaginary Parts:
[2. 4. 6.]


i. Use NumPy , Create an array with 5 dimensions and verify that it has 5 dimensions

In [ ]:
import numpy as np

# Create a 5-dimensional array
array_5d = np.random.random((2, 3, 4, 5, 6))

# Verify the number of dimensions
num_dimensions = array_5d.ndim

print("Array with 5 Dimensions:")
print(array_5d)
print(f"Number of Dimensions: {num_dimensions}")

Array with 5 Dimensions:
[[[[[8.12982945e-01 7.79033579e-01 1.73008450e-01 3.86198584e-01
     1.63870486e-01 3.36866449e-01]
    [8.75085027e-01 9.90740220e-01 6.24928257e-01 4.84202287e-02
     5.04365564e-01 8.57330992e-01]
    [1.20142566e-01 3.28815024e-01 1.88015960e-02 7.99603642e-01
     3.25916916e-01 2.12972235e-01]
    [9.98182383e-01 1.30526261e-01 8.06443610e-02 2.59484941e-01
     4.61328527e-01 7.74553948e-01]
    [8.39298786e-01 7.66310198e-01 9.71169407e-01 4.80236804e-02
     9.97396599e-01 1.36279112e-01]]

   [[4.50328540e-01 5.22620393e-01 7.57120952e-01 7.55256964e-01
     3.98525355e-01 4.74004488e-01]
    [7.31530795e-01 7.77216641e-02 1.47798794e-01 5.97096167e-01
     6.41826649e-01 8.51957613e-02]
    [9.82180150e-01 7.56097931e-01 6.62647458e-01 9.53148823e-01
     2.08366327e-01 9.55246569e-01]
    [8.94445469e-01 8.66644176e-04 2.46157601e-01 6.25295609e-01
     8.96880074e-01 3.89166813e-01]
    [8.98977847e-01 1.46094517e-01 1.09285213e-01 1.03222213e-01

ii. Using NumPy, Sort a boolean array

In [ ]:
import numpy as np

# Create a boolean array
boolean_array = np.array([True, False, True, False, True])

# Sort the boolean array
sorted_boolean_array = np.sort(boolean_array)

print("Original Boolean Array:")
print(boolean_array)
print("Sorted Boolean Array:")
print(sorted_boolean_array)

Original Boolean Array:
[ True False  True False  True]
Sorted Boolean Array:
[False False  True  True  True]


i. Write a NumPy program to find the real and imaginary parts of an array of complex numbers

In [ ]:
import numpy as np

# Create an array of complex numbers
complex_array = np.array([1 + 2j, 3 - 4j, 5 + 6j])

# Find the real and imaginary parts
real_parts = np.real(complex_array)
imaginary_parts = np.imag(complex_array)

print("Complex Array:")
print(complex_array)
print("Real Parts:")
print(real_parts)
print("Imaginary Parts:")
print(imaginary_parts)

Complex Array:
[1.+2.j 3.-4.j 5.+6.j]
Real Parts:
[1. 3. 5.]
Imaginary Parts:
[ 2. -4.  6.]


ii. Write a NumPy program to convert a NumPy array into a csv file

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Specify the file path
csv_file_path = "my_array.csv"

# Save the NumPy array to a CSV file
np.savetxt(csv_file_path, my_array, delimiter=",")

print(f"NumPy array has been saved to {csv_file_path}.")

NumPy array has been saved to my_array.csv.


Write a NumPy program to search the index of a given array in another given array. Sample Output:
Original NumPy array:
[[ 1 2 3]
[ 4 5 6]
[ 7 8 9]
[10 11 12]]
Searched array:
[4 5 6]
Index of the searched array in the original array:
[1]

In [29]:

import numpy as np

# Original NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Searched array
searched_array = np.array([4, 5, 6])

# Find the index of the searched array in the original array
index = np.where(np.all(original_array == searched_array, axis=1))[0]

# Print the original and searched arrays along with the index
print("Original NumPy array:")
print(original_array)
print("Searched array:")
print(searched_array)
print("Index of the searched array in the original array:", index)

Original NumPy array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Searched array:
[4 5 6]
Index of the searched array in the original array: [1]


Write a Pandas program to select the rows where the number of attempts in the examination is
greater than 2. Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura',
'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Expected Output:
Number of attempts in the examination is greater than 2:
name score attempts qualify
b Dima 9.0 3 no
d James NaN 3 no
f Michael 20.0 3 yes

In [30]:

import pandas as pd
import numpy as np

# Sample Python dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

# List labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create a DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Select rows where the number of attempts is greater than 2
result = df[df['attempts'] > 2]

# Display the result
print("Number of attempts in the examination is greater than 2:")
print(result)

Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes
